spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  expiration: 8640000000000000000000000000000000000000000000000000000000000000000000000000000000000000

geocode:
  api:
    key: ${GEOCODE_API_KEY}

logging:
  level:
    liquibase: INFO
    org.springframework: WARN
    org.hibernate: WARN