spring:
  application:
    name: backend
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:8Ff93GcOBjEq6nXJ42ZY6Uz4nX7L6GyHECifWQEVdTq4UMM6lZmYMIhWDO25ocP9bO6ziWW6GE18fgV7A8PsoQ==}
  expiration: 8640000000000000000000000000000000000000000000000000000000000000000000000000000000000000

geocode:
  api:
    key: ${GEOCODE_API_KEY:AIzaSyC8YnM2erJgoRgGuOpC2QQHPrexhOX09-w}

logging:
  level:
    liquibase: INFO
    org.springframework: WARN
    org.hibernate: WARN